<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MateHR.Domain\MateHR.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Recruitment\Commands\" />
    <Folder Include="Recruitment\DTOs\" />
    <Folder Include="Recruitment\Interfaces\" />
    <Folder Include="Recruitment\Mappings\" />
    <Folder Include="Recruitment\Validators\" />
    <Folder Include="Recruitment\Queries\" />
    <Folder Include="Tenants\DTOs\" />
    <Folder Include="Tenants\Interfaces\" />
    <Folder Include="Tenants\Mappings\" />
    <Folder Include="Tenants\Validators\" />
    <Folder Include="Tenants\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
  </ItemGroup>

</Project>
