<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Recruitment\Entities\" />
    <Folder Include="Recruitment\Aggregates\" />
    <Folder Include="Recruitment\DomainEvents\" />
    <Folder Include="Recruitment\ValueObjects\" />
    <Folder Include="Tenants\Aggregates\" />
    <Folder Include="Tenants\DomainEvents\" />
  </ItemGroup>

</Project>
